"""phase 7 initial schema

Revision ID: 7522c8f27b86
Revises: 
Create Date: 2026-09-11 09:31:50.773236
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7522c8f27b86'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('privacy_class', sa.String(length=16), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_providers_kind'), 'ai_providers', ['kind'], unique=False)
    op.create_table('ai_requests',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('routed_provider', sa.String(length=64), nullable=True),
    sa.Column('privacy_override', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_requests_created', 'ai_requests', ['created_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_event_ts', 'audit_log', ['event', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_event'), 'audit_log', ['event'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('mrn', sa.String(length=40), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=False)
    op.create_table('report_templates',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.String(length=32), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('template_key', sa.String(length=64), nullable=True),
    sa.Column('template_name', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('section_titles', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('routing_reason', sa.Text(), nullable=False),
    sa.Column('privacy_override_applied', sa.Boolean(), nullable=False),
    sa.Column('phi_redaction_applied', sa.Boolean(), nullable=False),
    sa.Column('terminology_substitutions', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amended_from', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_encounter_id'), 'reports', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_reports_session_id'), 'reports', ['session_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('transcripts',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_transcripts_encounter_id'), 'transcripts', ['encounter_id'], unique=False)
    op.create_table('encounters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=32), nullable=True),
    sa.Column('encounter_date', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('privacy_required', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_table('report_revisions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('report_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_revisions_report_id'), 'report_revisions', ['report_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('transcript_id', sa.String(length=64), nullable=False),
    sa.Column('segment_id', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id', 'segment_id', name='uq_segment_per_transcript')
    )
    op.create_index('ix_segments_transcript_position', 'transcript_segments', ['transcript_id', 'position'], unique=False)
    op.create_index(op.f('ix_transcript_segments_transcript_id'), 'transcript_segments', ['transcript_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.Column('device', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transcript_segments_transcript_id'), table_name='transcript_segments')
    op.drop_index('ix_segments_transcript_position', table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_report_revisions_report_id'), table_name='report_revisions')
    op.drop_table('report_revisions')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_transcripts_encounter_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_table('settings')
    op.drop_table('roles')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_session_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_encounter_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event'), table_name='audit_log')
    op.drop_index('ix_audit_event_ts', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_ai_requests_created', table_name='ai_requests')
    op.drop_table('ai_requests')
    op.drop_index(op.f('ix_ai_providers_kind'), table_name='ai_providers')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
