/* Phase 5 CI hardening: the WPF markup-compile temp project on Linux drops
   ImplicitUsings items, so this file lists them explicitly (duplicates from
   the SDK's implicit set are warnings at worst; TreatWarningsAsErrors=false). */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

// Report screen (Phase 6): generated draft (editable) → clinician review →
// explicit finalize → explicit approve. The lifecycle (draft → finalized →
// approved) and the hard rule "AI output is never automatically final"
// (spec §5/§8) are enforced SERVER-side; this view-model only reflects and
// drives it. Critical validation warnings block finalize/approve until the
// clinician acknowledges each with a recorded justification (spec §18).
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using MedicalScribe.WPF.Infrastructure;
using MedicalScribe.WPF.Models;
using MedicalScribe.WPF.Services;

namespace MedicalScribe.WPF.ViewModels;

public enum ReportState
{
    NoDraft,
    Draft,
    Finalized,
    Approved,
}

public sealed record ReportWarningRow(
    string Id,
    string Severity,
    string Code,
    string Message,
    bool Acknowledged);

public sealed partial class ReportViewModel : ObservableObject
{
    private readonly IServerStatusService _status;
    private readonly IApiClient _api;
    private readonly LiveTranscriptViewModel _transcript;

    public ReportViewModel(IServerStatusService status, IApiClient api, LiveTranscriptViewModel transcript)
    {
        _status = status;
        _api = api;
        _transcript = transcript;
        _status.StateChanged += (_, _) => OnUi(() =>
        {
            OnPropertyChanged(nameof(GenerateEnabled));
            OnPropertyChanged(nameof(SafetyBanner));
        });
    }

    private static void OnUi(Action action)
    {
        var dispatcher = System.Windows.Application.Current?.Dispatcher;
        if (dispatcher is not null && !dispatcher.CheckAccess())
        {
            dispatcher.BeginInvoke(action);
        }
        else
        {
            action();
        }
    }

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(CanFinalize))]
    [NotifyPropertyChangedFor(nameof(CanApprove))]
    private ReportState _state = ReportState.NoDraft;

    [ObservableProperty]
    private string _draftText = "";

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(CanFinalize))]
    private string _templateKey = "general-clinical-note";

    [ObservableProperty]
    private string? _message;

    [ObservableProperty]
    private bool _isGenerating;

    [ObservableProperty]
    private string? _reportId;

    [ObservableProperty]
    private string _encounterId = "encounter-1";

    /// <summary>Justification recorded with a warning acknowledgment.</summary>
    [ObservableProperty]
    private string _justification = "";

    public ObservableCollection<ReportWarningRow> Warnings { get; } = [];

    public string SafetyBanner => GenerateEnabled
        ? "Draft content is assistive documentation. Review before finalizing. AI text is never automatically a medical record."
        : "Report generation requires the server capability (feature flag report_generation).";

    public bool GenerateEnabled =>
        _status.State == ConnectionState.Online && _status.Manifest?.Features.ReportGeneration == true;

    public bool CanFinalize =>
        State == ReportState.Draft && !string.IsNullOrWhiteSpace(DraftText) && ReportId is not null;

    public bool CanApprove => State == ReportState.Finalized;

    public int BlockingCriticals => Warnings.Count(w =>
        w.Severity == "critical" && !w.Acknowledged);

    // -- generation ---------------------------------------------------------------

    [RelayCommand]
    private async Task GenerateAsync()
    {
        if (!GenerateEnabled)
        {
            Message = "Server has not enabled report generation yet.";
            return;
        }
        var source = _transcript.SessionId is not null
            ? new ReportDraftRequestDto(null, _transcript.SessionId, TemplateKey)
            : string.IsNullOrWhiteSpace(_transcript.FullText)
                ? null
                : new ReportDraftRequestDto(_transcript.FullText, null, TemplateKey);
        if (source is null)
        {
            Message = "Nothing to draft from — dictate or type a transcript first.";
            return;
        }
        IsGenerating = true;
        try
        {
            var draft = await _api.CreateReportDraftAsync(source, EncounterId);
            ReportId = draft.ReportId;
            await LoadWarnings(draft.Warnings);
            DraftText = RenderSections(await _api.GetReportAsync(draft.ReportId));
            State = ReportState.Draft;
            Message = $"Draft generated by '{draft.Provider}'"
                      + (draft.TerminologySubstitutions > 0
                          ? $" · {draft.TerminologySubstitutions} terminology normalizations applied to the prompt"
                          : "")
                      + $" · {Warnings.Count} validation warnings — review before finalizing.";
        }
        catch (ApiException ex)
        {
            Message = $"Generation failed: {ex.DetailMessage}";
        }
        finally
        {
            IsGenerating = false;
        }
    }

    // -- clinician lifecycle actions -----------------------------------------------

    [RelayCommand]
    private async Task FinalizeAsync()
    {
        if (!CanFinalize)
        {
            Message = BlockingCriticals > 0
                ? $"{BlockingCriticals} critical warnings must be acknowledged (with justification) before finalizing."
                : "Nothing to finalize.";
            return;
        }
        await SaveEditsAsync();
        try
        {
            var report = await _api.FinalizeReportAsync(ReportId!);
            ApplyReport(report);
            Message = "Finalized — approval is a separate explicit action.";
        }
        catch (ApiException ex)
        {
            Message = $"Finalize rejected: {ex.DetailMessage}";
            await RefreshAsync();
        }
    }

    [RelayCommand]
    private async Task ApproveAsync()
    {
        if (!CanApprove)
        {
            Message = "Approve requires a finalized report (explicit two-step).";
            return;
        }
        try
        {
            var report = await _api.ApproveReportAsync(ReportId!);
            ApplyReport(report);
            Message = "Approved — this version is now immutable; corrections start an amendment.";
        }
        catch (ApiException ex)
        {
            Message = $"Approve rejected: {ex.DetailMessage}";
            await RefreshAsync();
        }
    }

    [RelayCommand]
    private async Task AmendAsync()
    {
        if (State != ReportState.Approved || ReportId is null)
        {
            Message = "Amendment starts from an approved report.";
            return;
        }
        try
        {
            var report = await _api.AmendReportAsync(ReportId);
            ApplyReport(report);
            Message = "Amendment draft created (linked to the approved version).";
        }
        catch (ApiException ex)
        {
            Message = $"Amendment failed: {ex.DetailMessage}";
        }
    }

    [RelayCommand]
    private async Task ReopenDraftAsync()
    {
        if (State == ReportState.Approved)
        {
            Message = "Approved reports are immutable — create an amendment instead.";
            return;
        }
        if (ReportId is null)
        {
            State = ReportState.NoDraft;
            return;
        }
        try
        {
            var report = await _api.ReopenReportAsync(ReportId);
            ApplyReport(report);
            Message = "Reopened for editing.";
        }
        catch (ApiException ex)
        {
            Message = $"Reopen rejected: {ex.DetailMessage}";
            await RefreshAsync();
        }
    }

    [RelayCommand]
    private async Task AcknowledgeSelectedAsync(ReportWarningRow? row)
    {
        if (row is null || ReportId is null)
        {
            return;
        }
        if (string.IsNullOrWhiteSpace(Justification) || Justification.Trim().Length < 3)
        {
            Message = "Acknowledgment requires a recorded justification (≥3 chars).";
            return;
        }
        try
        {
            var report = await _api.AcknowledgeWarningAsync(
                ReportId, row.Id, Justification.Trim());
            await LoadWarnings(report.Warnings);
            Message = $"Warning acknowledged with recorded justification.";
        }
        catch (ApiException ex)
        {
            Message = $"Acknowledgment rejected: {ex.DetailMessage}";
        }
    }

    [RelayCommand]
    private async Task SaveEditsAsync()
    {
        if (ReportId is null || State is not (ReportState.Draft or ReportState.Finalized))
        {
            return;
        }
        // The report view edits sections as a single markdown document;
        // section-splitting happens by the ## headings the generator emits.
        var sections = SplitIntoSections(DraftText);
        if (sections.Count == 0)
        {
            return;
        }
        try
        {
            await _api.PatchReportSectionsAsync(ReportId, sections);
            Message = "Edits saved (clinician revision).";
        }
        catch (ApiException ex)
        {
            Message = $"Save rejected: {ex.DetailMessage}";
        }
    }

    [RelayCommand]
    private async Task RefreshAsync()
    {
        if (ReportId is null)
        {
            return;
        }
        try
        {
            var report = await _api.GetReportAsync(ReportId);
            if (report is not null)
            {
                ApplyReport(report);
            }
        }
        catch (ApiException ex)
        {
            Message = $"Refresh failed: {ex.DetailMessage}";
        }
    }

    // -- helpers --------------------------------------------------------------------

    private void ApplyReport(ReportDto report)
    {
        _lastSectionIds.Clear();
        _lastSectionIds.AddRange(report.Sections.Select(s => s.Id));
        ReportId = report.ReportId;
        State = report.Status switch
        {
            "draft" => ReportState.Draft,
            "finalized" => ReportState.Finalized,
            "approved" => ReportState.Approved,
            _ => ReportState.NoDraft,
        };
        TemplateKey = report.TemplateKey ?? TemplateKey;
        DraftText = RenderSections(report);
        _ = LoadWarnings(report.Warnings);
    }

    private async Task LoadWarnings(List<ReportWarningDto> warnings)
    {
        Warnings.Clear();
        foreach (var w in warnings)
        {
            Warnings.Add(new ReportWarningRow(w.Id, w.Severity, w.Code, w.Message, w.Acknowledged));
        }
        OnPropertyChanged(nameof(BlockingCriticals));
        OnPropertyChanged(nameof(CanFinalize));
        await Task.CompletedTask;
    }

    private static string RenderSections(ReportDto? report)
    {
        if (report is null)
        {
            return "";
        }
        var sb = new StringBuilder();
        foreach (var section in report.Sections)
        {
            if (sb.Length > 0)
            {
                sb.AppendLine().AppendLine();
            }
            sb.Append("## ").AppendLine(string.IsNullOrEmpty(section.Title) ? section.Id : section.Title);
            sb.AppendLine(section.Missing ? "[[MISSING]]" : section.Markdown);
        }
        return sb.ToString().TrimEnd();
    }

    /// <summary>Split the edited document back into sections on ## headings.
    /// Section ids come from the loaded report's section order — the split
    /// is positional, so deleting a heading re-merges into the previous
    /// section (safe: nothing is silently dropped from the document).</summary>
    private Dictionary<string, string> SplitIntoSections(string text)
    {
        var result = new Dictionary<string, string>();
        var known = CurrentSectionIds();
        var current = known.FirstOrDefault();
        var buffer = new List<string>();
        foreach (var line in text.Split('\n'))
        {
            var trimmed = line.TrimEnd('\r').Trim();
            if (trimmed.StartsWith("## ", StringComparison.Ordinal))
            {
                if (current is not null && buffer.Count > 0)
                {
                    result[current] = string.Join('\n', buffer).Trim();
                }
                buffer.Clear();
                var title = trimmed[3..].Trim();
                current = MatchSectionId(known, title) ?? current;
                continue;
            }
            buffer.Add(line);
        }
        if (current is not null && buffer.Count > 0)
        {
            result[current] = string.Join('\n', buffer).Trim();
        }
        return result;
    }

    private readonly List<string> _lastSectionIds = new();

    private List<string> CurrentSectionIds() => _lastSectionIds;

    private static string? MatchSectionId(IEnumerable<string> ids, string title)
    {
        var normalized = title.Replace(' ', '_').ToLowerInvariant();
        return ids.FirstOrDefault(id => id == normalized)
               ?? ids.FirstOrDefault(id => normalized.Contains(id, StringComparison.Ordinal));
    }
}
